# Generated by Django 4.2.8 on 2024-02-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group", models.IntegerField(verbose_name="所属群聊")),
                ("content", models.TextField(verbose_name="消息内容")),
                ("send_time", models.DateTimeField(auto_now=True, verbose_name="发送时间")),
            ],
            options={
                "verbose_name": "群聊消息",
                "verbose_name_plural": "群聊消息",
            },
        ),
    ]
