# Generated by Django 4.2.4 on 2024-02-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='recruit_message',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='招募信息标识符')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('volume', models.CharField(max_length=3, verbose_name='就餐人数')),
                ('grade', models.CharField(max_length=3, verbose_name='年级')),
                ('create_time', models.DateTimeField(verbose_name='招募开始时间')),
                ('end_time', models.DateTimeField(verbose_name='招募截止时间')),
                ('dinner_time', models.DateTimeField(verbose_name='用餐时间')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('form', models.CharField(max_length=20, verbose_name='样式')),
                ('taste', models.CharField(max_length=20, verbose_name='口味')),
                ('image', models.ImageField(upload_to='images/', verbose_name='美团店铺截图')),
                ('is_complete', models.BooleanField(default=False, verbose_name='是否完成')),
                ('user', models.ManyToManyField(related_name='recruit_messages', to='user.user')),
            ],
        ),
    ]
