# Generated by Django 4.2.8 on 2024-02-13 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appraise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "star",
                    models.SmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="星数",
                    ),
                ),
            ],
            options={
                "verbose_name": "评价信息",
                "verbose_name_plural": "评价信息",
            },
        ),
        migrations.CreateModel(
            name="MealInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20, verbose_name="标题")),
                ("content", models.TextField(verbose_name="详情")),
                (
                    "member_num",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                2, message="至少两人约饭"
                            )
                        ],
                        verbose_name="约饭总人数",
                    ),
                ),
                (
                    "grade",
                    models.SmallIntegerField(
                        choices=[
                            (1, "大一"),
                            (2, "大二"),
                            (3, "大三"),
                            (4, "大四"),
                            (5, "研一"),
                            (6, "研二"),
                            (7, "研三"),
                            (8, "博一"),
                            (9, "博二"),
                            (10, "博三"),
                            (11, "博四"),
                        ],
                        verbose_name="年级",
                    ),
                ),
                ("location", models.CharField(max_length=30, verbose_name="位置")),
                (
                    "cost",
                    models.SmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="你倒贴请吃饭？"
                            )
                        ],
                        verbose_name="人均消费",
                    ),
                ),
                (
                    "type",
                    models.SmallIntegerField(
                        choices=[
                            (1, "中餐"),
                            (2, "火锅"),
                            (3, "烧烤"),
                            (4, "西餐"),
                            (5, "韩料"),
                            (6, "日料"),
                            (7, "甜品"),
                            (8, "其它"),
                        ],
                        verbose_name="种类",
                    ),
                ),
                ("end_time", models.DateTimeField(verbose_name="招募截止时间")),
                ("meal_time", models.DateTimeField(verbose_name="吃饭时间")),
                (
                    "image1",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/", verbose_name="图片1"
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/", verbose_name="图片2"
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/", verbose_name="图片3"
                    ),
                ),
                (
                    "is_complete",
                    models.BooleanField(default=False, verbose_name="是否完成"),
                ),
            ],
            options={
                "verbose_name": "约饭信息",
                "verbose_name_plural": "约饭信息",
            },
        ),
        migrations.CreateModel(
            name="recruit_message",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="信息标识符",
                    ),
                ),
                ("title", models.CharField(max_length=20, verbose_name="标题")),
                ("content", models.TextField(verbose_name="详情")),
                (
                    "member_num",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                2, message="至少两人约饭"
                            )
                        ],
                        verbose_name="约饭总人数",
                    ),
                ),
                (
                    "grade",
                    models.SmallIntegerField(
                        choices=[
                            (1, "大一"),
                            (2, "大二"),
                            (3, "大三"),
                            (4, "大四"),
                            (5, "研一"),
                            (6, "研二"),
                            (7, "研三"),
                            (8, "博一"),
                            (9, "博二"),
                            (10, "博三"),
                            (11, "博四"),
                        ],
                        verbose_name="年级",
                    ),
                ),
                ("location", models.CharField(max_length=30, verbose_name="地点")),
                (
                    "type",
                    models.SmallIntegerField(
                        choices=[
                            (1, "中餐"),
                            (2, "火锅"),
                            (3, "烧烤"),
                            (4, "西餐"),
                            (5, "韩料"),
                            (6, "日料"),
                            (7, "甜品"),
                            (8, "其它"),
                        ],
                        verbose_name="种类",
                    ),
                ),
                (
                    "spicy",
                    models.SmallIntegerField(
                        choices=[(1, "不辣"), (2, "微辣"), (3, "中辣"), (4, "重辣")],
                        verbose_name="辣度",
                    ),
                ),
                ("end_time", models.DateTimeField(verbose_name="招募截止时间")),
                ("dinner_time", models.DateTimeField(verbose_name="用餐时间")),
                (
                    "image",
                    models.ImageField(upload_to="images/", verbose_name="美团店铺截图"),
                ),
                (
                    "is_complete",
                    models.BooleanField(default=False, verbose_name="是否完成"),
                ),
                ("likes", models.SmallIntegerField(default=0, verbose_name="点赞数")),
            ],
            options={
                "verbose_name": "招募信息",
                "verbose_name_plural": "招募信息",
            },
        ),
        migrations.CreateModel(
            name="Share",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "cost",
                    models.SmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="你倒贴请吃饭？"
                            )
                        ],
                        verbose_name="人均消费",
                    ),
                ),
                ("location", models.CharField(max_length=30, verbose_name="位置")),
                (
                    "type",
                    models.SmallIntegerField(
                        choices=[
                            (1, "中餐"),
                            (2, "火锅"),
                            (3, "烧烤"),
                            (4, "西餐"),
                            (5, "韩料"),
                            (6, "日料"),
                            (7, "甜品"),
                            (8, "其它"),
                        ],
                        verbose_name="种类",
                    ),
                ),
                (
                    "image1",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/", verbose_name="图片1"
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/", verbose_name="图片2"
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/", verbose_name="图片3"
                    ),
                ),
                ("likes", models.SmallIntegerField(default=0, verbose_name="点赞数")),
            ],
            options={
                "verbose_name": "分享",
                "verbose_name_plural": "分享",
            },
        ),
    ]
