# Generated by Django 4.2.4 on 2024-02-16 13:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('square', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeftMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言',
            },
        ),
        migrations.AlterModelOptions(
            name='appraise',
            options={'verbose_name': '评价', 'verbose_name_plural': '评价'},
        ),
        migrations.AddField(
            model_name='mealinfo',
            name='joined_num',
            field=models.IntegerField(default=0, verbose_name='已应募人数'),
        ),
        migrations.AddField(
            model_name='mealinfo',
            name='post_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布者'),
        ),
        migrations.AddField(
            model_name='mealinfo',
            name='spicy',
            field=models.SmallIntegerField(choices=[(1, '不辣'), (2, '微辣'), (3, '中辣'), (4, '重辣')], default=1, verbose_name='辣度'),
        ),
        migrations.AlterField(
            model_name='appraise',
            name='recipient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='被评价者'),
        ),
        migrations.AlterField(
            model_name='mealinfo',
            name='cost',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='预期人均消费'),
        ),
        migrations.AlterField(
            model_name='mealinfo',
            name='grade',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, '大一'), (2, '大二'), (3, '大三'), (4, '大四'), (5, '研一'), (6, '研二'), (7, '研三'), (8, '博一'), (9, '博二'), (10, '博三'), (11, '博四')], max_length=8, verbose_name='期望年级'),
        ),
        migrations.AlterField(
            model_name='mealinfo',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片1'),
        ),
        migrations.AlterField(
            model_name='mealinfo',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片2'),
        ),
        migrations.AlterField(
            model_name='mealinfo',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片3'),
        ),
        migrations.AlterField(
            model_name='mealinfo',
            name='location',
            field=models.CharField(max_length=30, verbose_name='地点'),
        ),
        migrations.AlterField(
            model_name='mealinfo',
            name='meal_time',
            field=models.DateTimeField(verbose_name='用餐时间'),
        ),
        migrations.AlterField(
            model_name='mealinfo',
            name='participants',
            field=models.ManyToManyField(null=True, related_name='meal_infos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='share',
            name='cost',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='人均消费'),
        ),
        migrations.AlterField(
            model_name='share',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片1'),
        ),
        migrations.AlterField(
            model_name='share',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片2'),
        ),
        migrations.AlterField(
            model_name='share',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片3'),
        ),
        migrations.AlterField(
            model_name='share',
            name='location',
            field=models.CharField(max_length=30, verbose_name='地点'),
        ),
        migrations.AlterField(
            model_name='share',
            name='post_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布者'),
        ),
        migrations.DeleteModel(
            name='recruit_message',
        ),
        migrations.AddField(
            model_name='leftmessage',
            name='meal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='square.mealinfo', verbose_name='对应约饭记录'),
        ),
        migrations.AddField(
            model_name='leftmessage',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='留言者'),
        ),
    ]
