# Generated by Django 4.2.4 on 2024-02-25 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('square', '0004_share_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraise',
            name='done',
            field=models.BooleanField(default=False, verbose_name='是否已评价'),
        ),
        migrations.AddField(
            model_name='appraise',
            name='meal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='square.mealinfo', verbose_name='对应约饭记录'),
        ),
        migrations.AddField(
            model_name='appraise',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评价者'),
        ),
        migrations.AddField(
            model_name='mealinfo',
            name='is_full',
            field=models.BooleanField(default=False, verbose_name='是否满员'),
        ),
        migrations.AddField(
            model_name='mealinfo',
            name='is_overdue',
            field=models.BooleanField(default=False, verbose_name='是否过期'),
        ),
        migrations.AddField(
            model_name='share',
            name='liked_by',
            field=models.ManyToManyField(related_name='likeds', to=settings.AUTH_USER_MODEL, verbose_name='点赞者'),
        ),
        migrations.AlterField(
            model_name='appraise',
            name='recipient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appraises', to=settings.AUTH_USER_MODEL, verbose_name='被评价者'),
        ),
        migrations.AlterField(
            model_name='mealinfo',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='是否吃完'),
        ),
        migrations.AlterField(
            model_name='mealinfo',
            name='participants',
            field=models.ManyToManyField(related_name='meal_infos', to=settings.AUTH_USER_MODEL, verbose_name='吃饭者'),
        ),
    ]
