# Generated by Django 4.2.4 on 2024-02-20 14:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("square", "0004_alter_mealinfo_participants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mealinfo",
            name="participants",
            field=models.ManyToManyField(
                null=True, related_name="meal_infos", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
