# Generated by Django 4.2.4 on 2024-02-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('square', '0005_appraise_done_appraise_meal_appraise_sender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appraise',
            old_name='sender',
            new_name='giver',
        ),
        migrations.RemoveField(
            model_name='appraise',
            name='done',
        ),
    ]
