# Generated by Django 4.2.4 on 2024-02-27 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('square', '0006_rename_sender_appraise_giver_remove_appraise_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraise',
            name='giver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='give_appraises', to=settings.AUTH_USER_MODEL, verbose_name='评价者'),
        ),
        migrations.AlterField(
            model_name='appraise',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='square.mealinfo', verbose_name='对应约饭记录'),
        ),
        migrations.AlterField(
            model_name='appraise',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_appraises', to=settings.AUTH_USER_MODEL, verbose_name='被评价者'),
        ),
        migrations.AlterField(
            model_name='leftmessage',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='square.mealinfo', verbose_name='对应约饭记录'),
        ),
        migrations.AlterField(
            model_name='leftmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='留言者'),
        ),
        migrations.AlterField(
            model_name='mealinfo',
            name='post_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布者'),
        ),
    ]
