# Generated by Django 4.2.4 on 2024-03-02 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('square', '0005_alter_mealinfo_participants'),
        ('square', '0007_alter_appraise_giver_alter_appraise_meal_and_more'),
    ]

    operations = [
    ]
