# Generated by Django 4.2.4 on 2024-03-02 09:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('square', '0008_merge_20240302_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealinfo',
            name='participants',
            field=models.ManyToManyField(related_name='meal_infos', to=settings.AUTH_USER_MODEL, verbose_name='吃饭者'),
        ),
    ]
