version: "3.8"

services:
### Redis container ##########################################
# 如果需要 redis 可以取消下面几行注释
# 在 django 程序中 redis 服务的 ip 地址可以直接填 redis
# redis:
# image: registry.cn-hangzhou.aliyuncs.com/ziqiang_studio/redis:latest
# container_name: YOUR_PROJECT_NAME-redis
# restart: always
# networks:
# - app-net
### MYSQL container #########################################
  db:
    image: 7e6df4470869             #  服务器上的mysql8.0镜像
    container_name: fuguang_mysql
    environment:
      MYSQL_ROOT_PASSWORD: "q49vfjfHTnKsyIC"
      MYSQL_DATABASE: "fuguang"
      MYSQL_USER: "fg" # 数据库用户名
      MYSQL_PASSWORD: "ExUG9zI8tcIF1GMzXja" # 用户密码
    volumes:
      - /home/zq_meal/FuGuang/lib/mysql:/var/lib/mysql
      - /home/zq_meal/FuGuang/common/mysql.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"  # 指定宿主机端口与容器端口映射关系，宿主机:容器
    restart: always # 容器随docker启动自启
    networks:
      - app-net
### Django container #########################################
  meal:
    image: fuguang_default # 将此处更换为之前构建的镜像名
    depends_on:
      - db
    restart: always
    container_name: fuguang_django # 将 YOUR_PROJECT_NAME 更换为自己项目的名字
    networks:
      - app-net
      - traefik
    labels:
      traefik.enable: true
      # 下面三行的xxx都要修改为自己项目的名字，也就是
      traefik.http.routers.meal.rule: Host(`api.meal.temp.ziqiang.net.cn`)
      traefik.http.routers.meal.entrypoints: websecure
      traefik.http.services.meal.loadbalancer.server.port: 8081 # 将YOUR_PORT 更改为相应端口
### Add Network Bridge info #########################################
networks:
  app-net: {}
  traefik:
    external: true
