# Generated by Django 4.2.4 on 2024-02-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='学号')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('phone_number', models.CharField(max_length=20, verbose_name='电话')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
    ]
