# Generated by Django 4.2.4 on 2024-02-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='star',
            field=models.IntegerField(default=5, verbose_name='评价星数'),
        ),
    ]
