# Generated by Django 4.2.4 on 2024-02-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='appraise_num',
            field=models.IntegerField(default=0, verbose_name='被评价次数'),
        ),
    ]
