# Generated by Django 4.2 on 2024-02-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0002_alter_user_private_letter"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="user",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="password",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_permissions",
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.IntegerField(
                choices=[(0, "未知"), (1, "男"), (2, "女")], default=0, verbose_name="性别"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="grade",
            field=models.IntegerField(default=0, verbose_name="年级"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_authenticated",
            field=models.BooleanField(default=True, verbose_name="是否激活"),
        ),
        migrations.AddField(
            model_name="user",
            name="openid",
            field=models.CharField(
                max_length=64, null=True, unique=True, verbose_name="微信openid"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="wechat",
            field=models.CharField(default="", max_length=25, verbose_name="wechat"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="管理员"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False, verbose_name="超级用户"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=20, unique=True, verbose_name="用户名"),
        ),
    ]
