# Generated by Django 4.2 on 2024-02-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_alter_user_managers_user_date_joined_user_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=20, null=True, verbose_name="密码"),
        ),
    ]
