# Generated by Django 4.2 on 2024-02-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="密码"
            ),
        ),
    ]
