# Generated by Django 4.2 on 2024-02-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="邮箱"
            ),
        ),
    ]
